language: java

sudo: false
dist: trusty

# Specify which branches/tags that we do not want to be built: r5.0.0-M5
branches:
  except:
    - /^r\d.*$/

before_install:
# Get latest install-jdk.sh script
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
# https://github.com/travis-ci/travis-ci/issues/8408
  - unset _JAVA_OPTIONS

matrix:
  include:
# Java 10 "Oracle JDK" (not yet provided by Travis CI)
    - env: JDK='Oracle JDK 10'
      install: . ./install-jdk.sh -F 10 -L BCL
# Java 10 "OpenJDK"
    - env: JDK='OpenJDK 10' JACOCO='-PenableJaCoCo' TOOLING='-Dplatform.tooling.support.tests.enabled=true'
      install: . ./install-jdk.sh -F 10 -L GPL
# Java 11 "Oracle JDK"
    - env: JDK='Oracle JDK 11'
      install: . ./install-jdk.sh -F 11 -L BCL

script:
# Display Gradle, Groovy, JVM and other versions
  - ./gradlew --version
# Build JUnit 5
  - ./gradlew --scan --stacktrace --warning-mode=all ${JACOCO} ${TOOLING} build

# If variable JACOCO is set, run JaCoCo report and send report to codecov.io after build success
after_success:
  - test -v JACOCO && ./gradlew ${JACOCO} jacocoRootReport && bash <(curl -s https://codecov.io/bash) || true
